### PR TITLE
Testing upgrade to 0.6.5

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- *Description of why you made this PR*

2 versions are released since latest master update

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
:+1:

**Comment by Thovi98** [comment]
(I don't have write rights in this repo)

**Comment by alexAubin** [comment]
@Thovi98 : you should have rights now :stuck_out_tongue_winking_eye:

**Pull request merged**
