### PR TITLE
Testing

### LINKED ISSUE #44: Remove services after uninstall application
### Describe the bug
After uninstall application bookwyrm_ynh on my yunohost (v11.2.4) server, the ynh autodiag log 3 warnings about unknown services : 
- bookwyrm-beat
- bookwyrm-server
- bookwyrm-worker.

Workaround the problem by applying manually this : 
```
$ sudo yunohost service remove bookwyrm-beat
Success! Service 'bookwyrm-beat' removed
$ sudo yunohost service remove bookwyrm-server
Success! Service 'bookwyrm-server' removed
$ sudo yunohost service remove bookwyrm-worker
Success! Service 'bookwyrm-worker' removed
```

### Context

- Hardware: *VPS bought online
- YunoHost version: 11.2.4
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  no

### Logs
```
[WARNING] Service bookwyrm-beat is unknown 🙁
  - You can try to restart the service, and if it doesn't work, have a look at the service logs in the webadmin (from the command line, you can do this with 'yunohost service restart bookwyrm-beat' and 'yunohost service log bookwyrm-beat').
[WARNING] Service bookwyrm-server is unknown 🙁
  - You can try to restart the service, and if it doesn't work, have a look at the service logs in the webadmin (from the command line, you can do this with 'yunohost service restart bookwyrm-server' and 'yunohost service log bookwyrm-server').
[WARNING] Service bookwyrm-worker is unknown 🙁
  - You can try to restart the service, and if it doesn't work, have a look at the service logs in the webadmin (from the command line, you can do this with 'yunohost service restart bookwyrm-worker' and 'yunohost service log bookwyrm-worker').
```

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

#48 
#49 
#50

Fixes 
#44
#46

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
LGTM but minor question about the set -a

**Comment by Thovi98** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
LGTM, cheers :+1:

**Pull request merged**
